source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

install! 'cocoapods', :deterministic_uuids => false

target 'SogoOnlineTTS' do
  # Depend on the generated SogouSpeech library.
  pod 'SogouSpeech', :path => '.'
end
